config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :items do
    resources :rentals, only: [:index, :show, :new, :create, :destroy]
  end

  resources :rentals, only: [] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord

  include PgSearch::Model
pg_search_scope :search_by_name_and_description,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true }
  }


  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_many :reviews, through: :rentals

  has_one_attached :photo

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 6 }
  validates :category, presence: true
  validates :category, inclusion: { in: ["Vehicles", "Tools", "Clothing", "Weddings", "Electronics", "Jewellery", "Bags", "Books", "Rooms", "Sports", "Boats", "Planes"] }
  validates :price_per_day, presence: true, numericality: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :item
  belongs_to :user
  has_one :review, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :end_date, comparison: { greater_than: :start_date }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :rental

  validates :item_score, presence: true, numericality: { only_integer: true }
  validates :item_comment, presence: true, length: { minimum: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :rentals, dependent: :destroy

  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :home_address, presence: true

  validates :first_name, uniqueness: {scope: [:last_name, :home_address] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :home_address, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :home_address, :photo])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index

if params[:category]
    @items = Item.where(category: params[:category]).order(:price_per_day)
elsif  params[:query]
  @items = Item.search_by_name_and_description(params[:query]).order(:price_per_day)
else
  @items = Item.all.order(:price_per_day)
end
  end

  def show
    @item = Item.find(params[:id])
    @rental = Rental.new()
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :category, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @rentals = Rental.where(user: current_user)
  end
  
  def show
    @rental = Rental.find(params[:id])
    @item = @rental.item
  end
  
  def new
    @item = Item.find(params[:item_id])
    @rental = Rental.new()
  end
  
  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.item = Item.find(params[:item_id])
    if @rental.save
      redirect_to edit_user_registration_path
    else
      render :new
    end
  end
  
  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy
    redirect_to edit_user_registration_path, status: :see_other
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<div class="main-container-flex">
  <div class="grid-container">

    <% @items.each do |item| %>
      <%= link_to item_path(item.id), class: "text" do %>

      <div class="item-card">
        <div class="item-card-photo-wrapper">
          <% if item.photo.attached? %>
            <%= cl_image_tag item.photo.key, height: 500, width: 500, crop: :fill %>
          <% else %>
            <%= image_tag "item-placeholder.png", class: "index-card-image" %>
          <% end %>
        </div>
        <div class="card-body">
          <div>
            <h5 class="card-title"><b><%= item.name %></b></h5>
            <p class="card-text">Only €<b><%= item.price_per_day %></b> per day </p>
          </div>
          <div>
            <%= image_tag "map-pin.jpg", class: "map-pin" %>
            <%= rand(1..20) %>km
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/items/new.html.erb
<div class="main-container-block">
  <div class="itemnew-form-container">
    <h1>Add a new item to your offerings!</h1>
    <%= simple_form_for @item do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :category, collection: ["Vehicles", "Tools", "Clothing", "Weddings", "Electronics", "Jewellery", "Bags", "Books", "Rooms", "Sports", "Boats", "Planes"] %>
      <%= f.input :price_per_day %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, "Create new item", class: "button-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="main-container-flex">
  <div class="itemshow">
    <div class="itemshow-left">
      <% if @item.photo.attached? %>
        <%= cl_image_tag @item.photo.key, height: 500, width: 500, crop: :fill %>
      <% else %>
        <%# <%= image_tag "https://source.unsplash.com/random/500x500/?#{@item.category}" %>
        <%# <%= image_tag "power_drill_static.png", class: "itemshow-picture" %>
        <%= image_tag "item-placeholder.png", class: "itemshow-picture" %>
      <% end %>
      <br>
      <%# link_to("<-- Back to overview", items_path) %>
    </div>
    
    <div class="itemshow-right">
      <div class="itemshow-header">
        <h1><%= @item.name %></h1>
        <p><%= "posted by: #{@item.user.first_name} #{@item.user.last_name}" %></p>
      </div>
      <div class="itemshow-description">
        <p><%= @item.description %></p>
      </div>
      <div class="itemshow-reviews-wrapper">
        <%= image_tag "scroll-chevrons.png", class: "itemshow-scroll-chevrons-left" %>
        <% 3.times do %>
          <div class="review-card">
            <p>I absolutely loved renting this item - it was much more convenient and affordable to rent it compared to buying it.</p>
            <div class="review-score-box">
              <%= image_tag "full-rating-star.png", class: "itemshow-full-star" %>
              <p>5</p>
            </div>
          </div>
        <% end %>
        <%= image_tag "scroll-chevrons.png", class: "itemshow-scroll-chevrons-right" %>
      </div>
      <div class="item-data-wrapper">
        <p><%= "Starting at € #{@item.price_per_day}" %></p>
        <div class="avg-rating-container">
          <p>Rated at: </p>
          <%= image_tag "full-rating-star.png", class: "itemshow-full-star" %>
          <p>4.2</p>
        </div>
      </div>
      <div data-controller="bookingbar">
        <div class="hidden" id="overlay" data-bookingbar-target="bookingbackground"></div>
        <button class="button-primary w-100" id="itemshow-share-button" data-action="click->bookingbar#show">Book it!</button>
        <div class="booking-container hidden" data-bookingbar-target="bookingform">
          <div class="booking-container-content">
            <h1>Book this item</h1>
            <%= simple_form_for [@item, @rental] do |f| %>
              <%= f.input :start_date %>
              <%= f.input :end_date %>
              <%= f.button :submit, "Finalize booking", class: "button-primary w-100" %>
            <% end %>
            <button class="button-secondary w-100" data-action="click->bookingbar#hide">Back to item page</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeShare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <%= render "shared/category-browser"%>
      <%= render "shared/flashes" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="main-container-flex home-flex-aspects">
    <div class="home-page-content">
      <h1 class="home-title">sustainable.affordable.social.</h1>
      <h2 class="home-tag-line">share your belongings for a brighter future</h2>
    </div>
    <div class="home-page-button">
      <div style="background-color:white; width:305px; border:none; border-radius:40px">
        <%= link_to items_path do%>
          <button class="button-primary">explore what's for rent</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rentals/index.html.erb
<div class="main-container-block">
  <h1>All the rentals of <%= "#{current_user.first_name} #{current_user.last_name}" %></h1>
  <div class="grid-container">
    <% @rentals.each do |rental| %>
      <div class="rental-card">
        <h3><%= rental.item.name %></h3>
        <p><%= "Rental ID: #{rental.id}" %></p>
        <p>Start date: <%= rental.start_date %></p>
        <p>End date: <%= rental.end_date %></p>
        <% @rental_days = (Date.parse("#{rental.end_date.year}-#{rental.end_date.month}-#{rental.end_date.day}") - Date.parse("#{rental.start_date.year}-#{rental.start_date.month}-#{rental.start_date.day}")).to_int + 1 %>
        <p>Total price: €<%= @rental_days * rental.item.price_per_day %></p>
        <p>Renting from user: <%= "#{rental.item.user.first_name} #{rental.item.user.last_name}" %></p>
      <%= link_to("More details of this rental", item_rental_path(rental.item, rental)) %>
      <br>
      <%= link_to "Cancel this rental", item_rental_path(rental.item, rental), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/rentals/new.html.erb
  <h3>Book this item</h3>
  <%= simple_form_for [@item, @rental] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.button :submit, "Finalize booking", class: "button-primary w-100" %>
  <% end %>

app/views/rentals/show.html.erb
<div class="very-main-rental-show"style="text-align:center;" >
  <div class="backround-pic">
    <div class="main-rental-show"style="text-align:center;" >
      <h2><strong>Order Confirmed</strong></h2>
      <h3>Details of your rental</h3>


      <p><%= "Your rental with ID: #{@rental.id}" %></p>

      <p>Rented the following <%= @rental.item.category %>: <%= @rental.item.name %></p>
      <p>Start date: <%= @rental.start_date %></p>
      <p>End date: <%= @rental.end_date %></p>
      <% @rental_days = (Date.parse("#{@rental.end_date.year}-#{@rental.end_date.month}-#{@rental.end_date.day}") - Date.parse("#{@rental.start_date.year}-#{@rental.start_date.month}-#{@rental.start_date.day}")).to_int + 1 %>
      <p>Total days: <%= @rental_days %></p>

      <p>Price per day: <%= @rental.item.price_per_day %></p>
      <p>-------------- </p>
      <p><strong>Total price: <%= @rental_days * @rental.item.price_per_day %></strong></p>
      <p>User offering: <%= "#{@rental.item.user.first_name} #{@rental.item.user.last_name}" %></p>
      <p>User renting: <%= "#{current_user.first_name} #{current_user.last_name}" %></p>
      <%= link_to("Back to all your rentals", edit_user_registration_path) %>
      <br>
      <%= link_to "Cancel this rental", item_rental_path(@item, @rental), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

    </div>
  </div>
</div>

app/views/shared/_category-browser.html.erb
<div class="category-card-container-border">

  <div class="category-object-container">

    <div>
      <div>
        <p class="column-title">Transport</p>
      </div>
      <div class="category-card-container">
        <%= link_to items_path(category: "Vehicles" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/vehicle-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Vehicles
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Planes" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/plane-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Planes
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Boats" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/boat-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Boats
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div>
      <div>
        <p class="column-title">Fashion</p>
      </div>
      <div class="category-card-container">
        <%= link_to items_path(category: "Clothing" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/clothing-icon.png", class: "icon-format"%>
          </div>
          <div class="category-card-content category-card-text">
            Clothing
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Jewellery" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/jewellery-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Jewellery
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Bags" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/bag-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Bags
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div>
      <div>
        <p class="column-title">Utilities</p>
      </div>
      <div class="category-card-container">
        <%= link_to items_path(category: "Electronics" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/electronics-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Electronics
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Tools" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/tool-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Tools
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Books" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/book-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text" >
            Books
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div>
      <div>
        <p class="column-title">Other</p>
      </div>
      <div class="category-card-container">
        <%= link_to items_path(category: "Weddings" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/wedding-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Weddings
        </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Sports" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/sport-icon.png", class: "icon-format" %>
          </div>
          <div class="category-card-content category-card-text">
            Sports
          </div>
        </div>
        <% end %>

        <%= link_to items_path(category: "Rooms" ) do %>
        <div class="category-card">
          <div class="category-card-content">
            <%= image_tag "category_icons/room-icon.png", class: "icon-format"%>
          </div>
          <div class="category-card-content category-card-text">
            Rooms
          </div>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="footer-content">
    <p>GDPR</p>
    <p>Trademark</p>
    <p>Site map</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar-content">
    <%= link_to root_path, class:"text-decoration-none" do %>
    <div class="logo-container">
      <%= image_tag "logo.png", class: "navbar-logo" %>
      <div id=navbar-logo-text>

      </div>
    </div>
    <% end %>

    <%= form_with url: items_path, method: :get, class: "d-flex search-form-field" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control search-form-back",
    placeholder: "We have it all ..."
  %>
  <%= submit_tag "Search", class: "btn btn-primary search-button" %>
<% end %>

    <%= link_to edit_user_registration_path do %>
    <div class="avatar-container">
      <% if user_signed_in? && current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, height: 50, width: 50, crop: :fill, class: "avatar-bordered"%>
      <% else %>
        <%= image_tag "empty-avatar.png", class: "avatar-bordered" %>
      <% end %>  
    </div>
    <% end %>
  </div>
</div>